name: Deploy Automático Harmonia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executar comandos na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/harmonia
            git pull origin main
            
            # Atualiza Backend
            source venv/bin/activate
            pip install -r backend/requirements.txt
            sudo systemctl restart harmonia
            
            # Atualiza Frontend
            cd frontend
            npm install
            npm run build

